# Seed the base universal deck
puts "Seeding base universal deck..."

deck = Deck.find_or_create_by!(name: 'Mazo Base Universal') do |d|
  d.description = 'El mazo clasico de Cartas Contra la Formalidad. Funciona en cualquier pais hispanohablante.'
  d.status = :draft
  d.content_rating = :adult
  d.official = true
end

# Black cards (questions/prompts)
black_cards = [
  "Durante mi primera cita, descubri que mi acompanante era adicto/a a _____.",
  "_____ es lo unico que me mantiene despierto en las juntas de trabajo.",
  "El nuevo reality show de Netflix se llama '_____: La Historia No Contada'.",
  "Cuando era nino, sonaba con ser _____ de grande.",
  "La razon por la que fui despedido: _____.",
  "En mi curriculum puse como habilidad especial: _____.",
  "Mi mama siempre me dijo que nunca hiciera _____. Y mira donde estoy.",
  "_____ es la razon por la que ya no me invitan a las fiestas.",
  "El secreto de mi exito profesional es _____.",
  "Mi ex me dejo por _____.",
  "En la boda de mi hermano, el brindis fue sobre _____.",
  "_____ deberia ser un deporte olimpico.",
  "Lo ultimo que quieres escuchar en un hospital es '_____'.",
  "Necesito _____ para sobrevivir a las reuniones familiares.",
  "Mi terapeuta renuncio despues de que le conte sobre _____.",
  "_____ + _____ = Una noche inolvidable.",
  "El peor regalo de cumpleanos que he recibido fue _____.",
  "Mi vecino no me habla desde que vio _____.",
  "La razon por la que no duermo bien es _____.",
  "_____ es lo que realmente se discute en el grupo de WhatsApp familiar.",
  "Mi vida seria perfecta si no fuera por _____.",
  "El manual de supervivencia para el trabajo incluye _____.",
  "Quiero _____ grabado en mi lapida.",
  "Mi momento mas vergonzoso fue cuando _____ en publico.",
  "La nueva politica de la empresa prohibe _____.",
  "_____ es la razon por la que me vetaron del supermercado.",
  "Hoy aprendi que _____ es ilegal en 47 paises.",
  "Mi tia siempre pregunta por _____ en las reuniones.",
  "_____ arruino mi infancia.",
  "El presidente anuncio que ahora _____ es obligatorio.",
  "Senoras y senores, con ustedes: _____!",
  "No puedo creer que me hayan pagado por _____.",
  "Mi perro se comio _____ y ahora actua raro.",
  "_____ es la cura para la cruda.",
  "El nuevo sabor de helado es _____.",
  "Si pudiera viajar en el tiempo, cambiaria _____.",
  "Mi crush me rechazo porque le dije que me gustaba _____.",
  "_____ deberia ensenarse en las escuelas.",
  "La policia me detuvo por _____.",
  "Mi abuela guarda _____ debajo de su cama.",
  "El WiFi de mi casa se llama '_____'.",
  "_____ es mi personalidad entera.",
  "Fui trendy topic en Twitter por _____.",
  "Mi jefe me sorprendio haciendo _____ en la oficina.",
  "_____ esta prohibido en mi casa.",
  "La peor excusa que he dado para no ir a trabajar: _____.",
  "Mi vida amorosa se resume en _____.",
  "_____ es lo que realmente pienso durante las videollamadas.",
  "Encontre _____ en el historial de busqueda de mi papa.",
  "Mi biografia de Tinder dice: 'Busco a alguien que aprecie _____'.",
  "_____ no es un crimen pero deberia serlo.",
  "Me desperte a las 3am pensando en _____.",
  "El grupo de padres de familia esta enojado por _____.",
  "Mi mayor logro en la vida es _____.",
  "_____ es mi culpable placer.",
  "Antes de morir quiero experimentar _____.",
  "La persona a mi lado en el avion no paraba de hablar de _____.",
  "Mi gato me mira como si supiera que hice _____.",
  "_____ es la razon por la que el tequila y yo ya no somos amigos.",
  "En mi pueblo natal, _____ es tradicion.",
  "Mi madre descubrio _____ en mi cuarto.",
  "_____ es lo que necesito despues de este dia.",
  "El consultorio del dentista tiene un poster de _____.",
  "Mi plan para hacerme rico incluye _____.",
  "_____ cambio mi vida para siempre.",
  "Encontre _____ en la seccion de perdido y encontrado.",
  "La proxima pandemia sera causada por _____.",
  "_____ es la razon por la que bebo.",
  "Mi abuelo me heredo _____.",
  "El ingrediente secreto de la comida de mama es _____.",
  "_____ deberia ser el nuevo emoji.",
  "Mi look para la fiesta de oficina es _____.",
  "_____ es lo que finjo no saber hacer para no ayudar.",
  "El error de mi vida fue pensar que _____ era buena idea.",
  "Si fuera presidente, legalizaria _____.",
  "Mi alarma de las 6am me recuerda _____.",
  "_____ me traumo de por vida.",
  "La ultima vez que llore fue por _____.",
  "Mi amigo imaginario de la infancia era _____.",
  "_____ es lo unico que me hace feliz.",
  "Antes de dormir siempre pienso en _____.",
  "Mi peor decision de borracho fue _____.",
  "_____ es la mejor medicina.",
  "El siguiente presidente de Mexico sera _____.",
  "Mi psicologo toma notas cuando hablo de _____.",
  "_____ define a mi generacion.",
  "La receta secreta de la abuela incluye _____.",
  "Mi yo del futuro me odiaria por _____.",
  "_____ me hizo la persona que soy hoy.",
  "El ultimo mensaje en mi celular dice '_____'.",
  "_____ + _____ = El fin de mi carrera.",
  "Mis padres aun no saben que hice _____.",
  "_____ es lo que las peliculas de Disney nunca mostraron.",
  "Mi sueno recurrente involucra _____.",
  "_____ es la razon por la que no tengo amigos.",
  "El precio de _____ ha subido 300%.",
  "Mi mayor miedo es _____.",
  "_____ es lo unico que me mantiene cuerdo.",
  "La maestra me castigo por _____.",
  "Si pudiera, le diria al mundo que _____.",
]

# White cards (answers)
white_cards = [
  # People & Celebrities
  "Tu tia en las bodas",
  "El presidente en pijama",
  "Un payaso triste",
  "El vecino chismoso",
  "El nino del Oxxo",
  "Tu ex en su peor momento",
  "La senora de los tamales",
  "El guardia de seguridad bailando",
  "Tu yo de hace 10 anos",
  "El maestro de matematicas",
  "La suegra perfecta",
  "Un influencer sin WiFi",
  "El viejito del parque",
  "La Karen mexicana",
  "Tu crush de la secundaria",
  "El repartidor de Uber Eats",
  "Un millennial explicando memes",
  "El DJ de bodas",
  "La amiga que siempre llora",
  "El primo que nadie invito",

  # Actions & Situations
  "Llorar en el bano del trabajo",
  "Fingir que trabajas",
  "Mandar el mensaje al grupo equivocado",
  "Quedarse dormido en la junta",
  "Stalkear a tu ex",
  "Hacer dieta los lunes",
  "Ghostear a alguien",
  "Decir 'ahi nos vemos' y no ir",
  "Llegar tarde a todo",
  "Usar ropa interior de la suerte",
  "Cantar en la regadera",
  "Comer en secreto a las 3am",
  "Inventar excusas creativas",
  "Gastar el sueldo el primer dia",
  "Revisar el celular 100 veces",
  "Pretender que no viste el mensaje",
  "Salir de una conversacion incomoda",
  "Ensayar peleas en la regadera",
  "Hacer planes y cancelar",
  "Criticar a alguien y luego hacer lo mismo",

  # Objects & Things
  "Los memes de tu tia",
  "Un tequila a mediodia",
  "La chancla de tu mama",
  "El audio de 10 minutos",
  "Los tacos de la esquina",
  "La sabila de la abuela",
  "El Vick VapoRub",
  "Los frijoles de ayer",
  "El WiFi del vecino",
  "Las sobras del refri",
  "El peluche de la infancia",
  "Las fotos vergonzosas",
  "El regalo regifteado",
  "Los calcetines con hoyos",
  "La playlist de despecho",
  "El saldo de $3",
  "Las notificaciones ignoradas",
  "La ropa del gimnasio sin usar",
  "El telefono con la pantalla rota",
  "Los tuppers que nunca regresan",

  # Concepts & Abstract
  "Ansiedad social",
  "Problemas de compromiso",
  "Humor negro",
  "Procrastinacion extrema",
  "Verguenza ajena",
  "Crisis existencial",
  "Expectativas vs realidad",
  "Cringe puro",
  "Red flags ignoradas",
  "Decisiones cuestionables",
  "Trauma generacional",
  "Silencio incomodo",
  "Drama innecesario",
  "Nostalgia toxica",
  "Negacion profunda",
  "Desilusion continua",
  "Esperanzas falsas",
  "Chisme de calidad",
  "Arrepentimiento tardio",
  "Culpa catolica",

  # Pop Culture & Modern Life
  "Netflix y nada que ver",
  "El algoritmo de TikTok",
  "Fotos con filtro extremo",
  "Stories de LinkedIn",
  "Reuniones que pudieron ser emails",
  "La zona de amigos",
  "Ghosting profesional",
  "El outfit repetido",
  "Selfies en el espejo",
  "Citas por aplicacion",
  "Lives de madrugada",
  "Comentarios pasivo-agresivos",
  "La banda de Spotify",
  "Tweets borrachos",
  "El like accidental",
  "Las notificaciones de LinkedIn",
  "El correo con copia oculta",
  "El estado de 'escribiendo...'",
  "El leido sin respuesta",
  "Las stories de hace 3 anos",

  # Food & Drink
  "Tacos de canasta",
  "Mezcal artesanal",
  "El aguacate maduro",
  "Pozole de la abuela",
  "Salsa que pica de verdad",
  "La torta ahogada",
  "Elotes con todo",
  "El cafe de olla",
  "Churros con chocolate",
  "La birria de los domingos",
  "Esquites de la esquina",
  "El pulque de rancho",
  "Tamales de chipil",
  "La nieve de garrafa",
  "Carnitas recien hechas",
  "El champurrado",
  "Memelas con salsa",
  "El mole de tres dias",
  "Chicharron con limon",
  "La coca de vidrio",

  # Emotions & States
  "Esa sensacion despues de cancelar planes",
  "El segundo aire a las 2am",
  "La felicidad de un dia libre",
  "El terror del lunes",
  "La paz del silencio",
  "El vacio del domingo en la noche",
  "La satisfaccion de terminar una serie",
  "El panico antes de la fecha limite",
  "La libertad del ultimo dia de trabajo",
  "El hambre a medianoche",
  "La tristeza sin motivo",
  "El coraje contenido",
  "La alegria sospechosa",
  "El cansancio existencial",
  "La motivacion de 15 minutos",

  # Regional Expressions
  "No manches!",
  "Que oso!",
  "Esta canon",
  "Ando crudo/a",
  "Ya me dio el bajonsazo",
  "Que padre!",
  "Esta muy chido",
  "No hay de queso nomas de papa",
  "Ahorita",
  "Luego luego",
  "Simon",
  "Nel pastel",
  "Aguas!",
  "Que onda!",
  "Sale y vale",

  # Modern Problems
  "El precio de la gasolina",
  "Los impuestos",
  "El trafico de siempre",
  "La renta impagable",
  "El sistema de salud",
  "Los politicos de siempre",
  "La inflacion",
  "El calentamiento global",
  "Los bots de internet",
  "Las fake news",
  "El sistema educativo",
  "La burocracia mexicana",
  "Los baches eternos",
  "El agua cara",
  "La luz cortada",

  # Body & Health
  "El dolor de espalda cronico",
  "La resaca del siglo",
  "Las ojeras permanentes",
  "El estomago delicado",
  "Las rodillas que truenan",
  "La memoria selectiva",
  "El insomnio de 3am",
  "Los kilos de la pandemia",
  "La alergia eterna",
  "El estres acumulado",
  "La cadera que avisa el clima",
  "Los genes de la familia",
  "El metabolismo lento",
  "La vista cansada",
  "El pelo rebelde",

  # Miscellaneous
  "Un 'te lo dije' muy satisfactorio",
  "La venganza servida en plato frio",
  "El karma instantaneo",
  "La suerte del principiante",
  "El poder de la indiferencia",
  "La paz mental",
  "Un milagro inesperado",
  "La fe ciega",
  "Un plot twist de la vida",
  "El destino cruel",
  "Una coincidencia sospechosa",
  "El momento exacto",
  "La oportunidad perdida",
  "Una mentira piadosa",
  "La verdad incomoda",
]

# Create cards
puts "Creating #{black_cards.count} black cards..."
black_cards.each do |content|
  blank_count = content.scan('_____').count
  blank_count = 1 if blank_count.zero?

  deck.owned_cards.find_or_create_by!(content: content) do |c|
    c.card_type = :black
    c.pick_count = [blank_count, 3].min
  end
end

puts "Creating #{white_cards.count} white cards..."
white_cards.each do |content|
  deck.owned_cards.find_or_create_by!(content: content) do |c|
    c.card_type = :white
    c.pick_count = 1
  end
end

deck.update!(status: :published) if deck.playable?

puts "Base deck created with #{deck.black_cards.count} black cards and #{deck.white_cards.count} white cards"
